apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-ces-warp-config
  labels:
    {{- include "k8s-ces-assets.labels" . | nindent 4 }}
data:
  warp.yaml: |
    categories:
      {{- .Values.warp.categories | toYaml | nindent 6 }}

    defaultEntries:
      {{- .Values.warp.defaultEntries | toYaml | nindent 6 }}